import { randomUUID } from "node:crypto";
import { constants } from "node:fs";
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export const runtime = "nodejs";

type RobotRequest = {
  website: string;
  instruction: string;
  loginUrl?: string;
  username?: string;
  password?: string;
  expectedText?: string;
};

function cleanPayload(body: unknown): RobotRequest | string {
  if (!body || typeof body !== "object") return "Invalid payload";
  const raw = body as Record<string, unknown>;
  const website = String(raw.website ?? "").trim();
  const instruction = String(raw.instruction ?? "").trim();
  const loginUrl = String(raw.loginUrl ?? "").trim();
  const username = String(raw.username ?? "").trim();
  const password = String(raw.password ?? "").trim();
  const expectedText = String(raw.expectedText ?? "").trim();

  if (!website) return "Website URL is required";

  let parsed: URL;
  try {
    parsed = new URL(website);
  } catch {
    return "Website must be a valid absolute URL";
  }

  if (parsed.protocol !== "http:" && parsed.protocol !== "https:") {
    return "Only http and https URLs are supported";
  }

  const payload: RobotRequest = {
    website,
    instruction:
      instruction ||
      "Check the website availability and basic response health using Robot Framework.",
  };

  if (loginUrl) {
    try {
      const parsedLoginUrl = new URL(loginUrl);
      if (parsedLoginUrl.protocol !== "http:" && parsedLoginUrl.protocol !== "https:") {
        return "Only http and https login URLs are supported";
      }
      payload.loginUrl = loginUrl;
    } catch {
      return "Login URL must be a valid absolute URL";
    }
  }

  if (username) payload.username = username;
  if (password) payload.password = password;
  if (expectedText) payload.expectedText = expectedText;

  return payload;
}

function robotValue(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\$/g, "\\$").replace(/\r?\n/g, " ").trim();
}

function buildLoginTest(request: RobotRequest) {
  if (!request.username || !request.password) return "";

  const loginUrl = request.loginUrl || request.website;
  const expectedText = request.expectedText || "";

  return `
Login Flow Works
    [Documentation]    Attempts a real browser login using common username, password, and submit selectors.
    Open Browser    \${LOGIN_URL}    Chrome    options=add_argument("--headless=new");add_argument("--no-sandbox");add_argument("--disable-dev-shm-usage")
    Set Selenium Timeout    15s
    Input First Available    \${USERNAME}    css:input[type="email"]    css:input[name="email"]    css:input[name="username"]    css:input[id*="email"]    css:input[id*="user"]    css:input[type="text"]    css:input:not([type])
    Input First Available    \${PASSWORD}    css:input[type="password"]    css:input[name="password"]    css:input[id*="password"]
    Click First Available    css:button[type="submit"]    css:input[type="submit"]    xpath://button[contains(translate(normalize-space(.), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'login')]    xpath://button[contains(translate(normalize-space(.), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'sign in')]
    Wait Until Keyword Succeeds    20s    1s    Location Should Change From Login
    Run Keyword If    '\${EXPECTED_TEXT}' != ''    Page Should Contain    \${EXPECTED_TEXT}
    Capture Page Screenshot
    Close Browser
`;
}

function buildLoginKeywords(request: RobotRequest) {
  if (!request.username || !request.password) return "";

  return `
*** Keywords ***
Input First Available
    [Arguments]    \${value}    @{locators}
    FOR    \${locator}    IN    @{locators}
        \${found}=    Run Keyword And Return Status    Page Should Contain Element    \${locator}
        IF    \${found}
            Input Text    \${locator}    \${value}
            RETURN
        END
    END
    Fail    No matching input field was found.

Click First Available
    [Arguments]    @{locators}
    FOR    \${locator}    IN    @{locators}
        \${found}=    Run Keyword And Return Status    Page Should Contain Element    \${locator}
        IF    \${found}
            Click Element    \${locator}
            RETURN
        END
    END
    Fail    No matching submit control was found.

Location Should Change From Login
    \${current}=    Get Location
    Should Not Be Equal As Strings    \${current}    \${LOGIN_URL}
`;
}

function buildRobotFile(request: RobotRequest) {
  return `*** Settings ***
Documentation    Generated by SQA Test Studio.
${request.username && request.password ? "Library    SeleniumLibrary" : ""}

*** Variables ***
\${TARGET_URL}    ${robotValue(request.website)}
\${INSTRUCTION}    ${robotValue(request.instruction)}
\${LOGIN_URL}    ${robotValue(request.loginUrl || request.website)}
\${USERNAME}    ${robotValue(request.username || "")}
\${PASSWORD}    ${robotValue(request.password || "")}
\${EXPECTED_TEXT}    ${robotValue(request.expectedText || "")}

*** Test Cases ***
Website Responds Successfully
    [Documentation]    \${INSTRUCTION}
    \${urllib}=    Evaluate    __import__("urllib.request", fromlist=["urlopen"])
    \${response}=    Evaluate    $urllib.urlopen(r"""\${TARGET_URL}""", timeout=20)
    \${status}=    Evaluate    $response.status
    Should Be True    \${status} < 500
    Log    Website responded with HTTP \${status}
${buildLoginTest(request)}
${buildLoginKeywords(request)}
`;
}

async function findRobotExecutable() {
  const pathEntries = (process.env.PATH ?? "").split(path.delimiter).filter(Boolean);
  const names = process.platform === "win32" ? ["robot.exe", "robot.bat", "robot.cmd"] : ["robot"];

  for (const entry of pathEntries) {
    for (const name of names) {
      const candidate = path.join(entry, name);
      try {
        await access(candidate, constants.X_OK);
        return candidate;
      } catch {
        // Continue searching PATH.
      }
    }
  }

  return null;
}

function runRobot(executable: string, robotPath: string, outputDir: string) {
  return new Promise<{ code: number | null; stdout: string; stderr: string }>((resolve, reject) => {
    const args = ["--outputdir", outputDir, robotPath];
    const isWindowsScript = process.platform === "win32" && /\.(bat|cmd)$/i.test(executable);
    const child = spawn(executable, args, {
      shell: isWindowsScript,
      windowsHide: true,
    });
    let stdout = "";
    let stderr = "";

    child.stdout?.on("data", (chunk) => {
      stdout += String(chunk);
    });
    child.stderr?.on("data", (chunk) => {
      stderr += String(chunk);
    });
    child.on("error", reject);
    child.on("close", (code) => resolve({ code, stdout, stderr }));
  });
}

function parseRobotSummary(outputXml: string) {
  const statusMatches = [...outputXml.matchAll(/<status status="(PASS|FAIL)"[^>]*>/g)];
  const elapsedMatch = outputXml.match(/elapsed="([^"]+)"/);
  const messageMatches = [...outputXml.matchAll(/<msg[^>]*>([^<]+)<\/msg>/g)];
  const hasFailure = statusMatches.some((match) => match[1] === "FAIL");

  return {
    status: !hasFailure && statusMatches.length > 0 ? "passed" : "failed",
    elapsed: elapsedMatch?.[1] ?? null,
    message:
      messageMatches.at(-1)?.[1]?.replace(/&lt;/g, "<").replace(/&gt;/g, ">") ??
      "Robot Framework execution completed.",
  };
}

function setupResponse(message: string, scriptPath?: string) {
  return NextResponse.json(
    {
      status: "setup_required",
      message:
        "Robot Framework is not available to the app. Install it and make sure the robot command is on PATH.",
      detail: message,
      scriptPath,
    },
    { status: 503 },
  );
}

export async function POST(request: NextRequest) {
  const body = await request.json().catch(() => null);
  const payload = cleanPayload(body);

  if (typeof payload === "string") {
    return new Response(payload, { status: 400 });
  }

  const executable = await findRobotExecutable();
  if (!executable) {
    return setupResponse("robot command was not found on PATH");
  }

  const runId = randomUUID();
  const runDir = path.join(tmpdir(), "sqa-portal-robot", runId);
  const scriptPath = path.join(runDir, "sqa-test-studio.robot");
  const outputPath = path.join(runDir, "output.xml");

  await mkdir(runDir, { recursive: true });
  await writeFile(scriptPath, buildRobotFile(payload), "utf8");

  try {
    const result = await runRobot(executable, scriptPath, runDir);
    const outputXml = await readFile(outputPath, "utf8").catch(() => "");
    const summary = outputXml ? parseRobotSummary(outputXml) : null;

    if (result.code !== 0) {
      return NextResponse.json(
        {
          status: "failed",
          message: "Robot Framework test failed.",
          stdout: result.stdout.trim(),
          stderr: result.stderr.trim(),
          scriptPath,
          outputPath,
          summary,
        },
        { status: 500 },
      );
    }

    return NextResponse.json({
      status: "completed",
      runId,
      scriptPath,
      outputPath,
      summary,
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unable to start Robot Framework";
    return setupResponse(message, scriptPath);
  }
}
