/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ToolsQeRouteImport } from './routes/tools.qe'
import { Route as ToolsQaGeniusRouteImport } from './routes/tools.qa-genius'
import { Route as ToolsPerformanceRouteImport } from './routes/tools.performance'
import { Route as ToolsOrcaRouteImport } from './routes/tools.orca'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as PortalToolsRouteImport } from './routes/portal.tools'
import { Route as PortalTestbedsRouteImport } from './routes/portal.testbeds'
import { Route as PortalProjectsRouteImport } from './routes/portal.projects'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as HelpTutorialRouteImport } from './routes/help.tutorial'
import { Route as HelpFaqRouteImport } from './routes/help.faq'
import { Route as HelpContactRouteImport } from './routes/help.contact'
import { Route as HelpChatRouteImport } from './routes/help.chat'
import { Route as ToolsQaGeniusLibraryRouteImport } from './routes/tools.qa-genius.library'
import { Route as ToolsQaGeniusHistoryRouteImport } from './routes/tools.qa-genius.history'
import { Route as ToolsPerformanceScenariosRouteImport } from './routes/tools.performance.scenarios'
import { Route as ToolsPerformanceReportsRouteImport } from './routes/tools.performance.reports'
import { Route as ToolsOrcaSwarmsRouteImport } from './routes/tools.orca.swarms'
import { Route as ToolsOrcaLogsRouteImport } from './routes/tools.orca.logs'
import { Route as ToolsOrcaAgentsRouteImport } from './routes/tools.orca.agents'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ToolsQeRoute = ToolsQeRouteImport.update({
  id: '/tools/qe',
  path: '/tools/qe',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsQaGeniusRoute = ToolsQaGeniusRouteImport.update({
  id: '/tools/qa-genius',
  path: '/tools/qa-genius',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPerformanceRoute = ToolsPerformanceRouteImport.update({
  id: '/tools/performance',
  path: '/tools/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOrcaRoute = ToolsOrcaRouteImport.update({
  id: '/tools/orca',
  path: '/tools/orca',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const PortalToolsRoute = PortalToolsRouteImport.update({
  id: '/portal/tools',
  path: '/portal/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTestbedsRoute = PortalTestbedsRouteImport.update({
  id: '/portal/testbeds',
  path: '/portal/testbeds',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProjectsRoute = PortalProjectsRouteImport.update({
  id: '/portal/projects',
  path: '/portal/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/portal/admin',
  path: '/portal/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTutorialRoute = HelpTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => HelpRoute,
} as any)
const HelpFaqRoute = HelpFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => HelpRoute,
} as any)
const HelpContactRoute = HelpContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => HelpRoute,
} as any)
const HelpChatRoute = HelpChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => HelpRoute,
} as any)
const ToolsQaGeniusLibraryRoute = ToolsQaGeniusLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ToolsQaGeniusRoute,
} as any)
const ToolsQaGeniusHistoryRoute = ToolsQaGeniusHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ToolsQaGeniusRoute,
} as any)
const ToolsPerformanceScenariosRoute =
  ToolsPerformanceScenariosRouteImport.update({
    id: '/scenarios',
    path: '/scenarios',
    getParentRoute: () => ToolsPerformanceRoute,
  } as any)
const ToolsPerformanceReportsRoute = ToolsPerformanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ToolsPerformanceRoute,
} as any)
const ToolsOrcaSwarmsRoute = ToolsOrcaSwarmsRouteImport.update({
  id: '/swarms',
  path: '/swarms',
  getParentRoute: () => ToolsOrcaRoute,
} as any)
const ToolsOrcaLogsRoute = ToolsOrcaLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ToolsOrcaRoute,
} as any)
const ToolsOrcaAgentsRoute = ToolsOrcaAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ToolsOrcaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/runs': typeof RunsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/help/chat': typeof HelpChatRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/tutorial': typeof HelpTutorialRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/testbeds': typeof PortalTestbedsRoute
  '/portal/tools': typeof PortalToolsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tools/orca': typeof ToolsOrcaRouteWithChildren
  '/tools/performance': typeof ToolsPerformanceRouteWithChildren
  '/tools/qa-genius': typeof ToolsQaGeniusRouteWithChildren
  '/tools/qe': typeof ToolsQeRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tools/orca/agents': typeof ToolsOrcaAgentsRoute
  '/tools/orca/logs': typeof ToolsOrcaLogsRoute
  '/tools/orca/swarms': typeof ToolsOrcaSwarmsRoute
  '/tools/performance/reports': typeof ToolsPerformanceReportsRoute
  '/tools/performance/scenarios': typeof ToolsPerformanceScenariosRoute
  '/tools/qa-genius/history': typeof ToolsQaGeniusHistoryRoute
  '/tools/qa-genius/library': typeof ToolsQaGeniusLibraryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/runs': typeof RunsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/help/chat': typeof HelpChatRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/tutorial': typeof HelpTutorialRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/testbeds': typeof PortalTestbedsRoute
  '/portal/tools': typeof PortalToolsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tools/orca': typeof ToolsOrcaRouteWithChildren
  '/tools/performance': typeof ToolsPerformanceRouteWithChildren
  '/tools/qa-genius': typeof ToolsQaGeniusRouteWithChildren
  '/tools/qe': typeof ToolsQeRoute
  '/projects': typeof ProjectsIndexRoute
  '/tools/orca/agents': typeof ToolsOrcaAgentsRoute
  '/tools/orca/logs': typeof ToolsOrcaLogsRoute
  '/tools/orca/swarms': typeof ToolsOrcaSwarmsRoute
  '/tools/performance/reports': typeof ToolsPerformanceReportsRoute
  '/tools/performance/scenarios': typeof ToolsPerformanceScenariosRoute
  '/tools/qa-genius/history': typeof ToolsQaGeniusHistoryRoute
  '/tools/qa-genius/library': typeof ToolsQaGeniusLibraryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRouteWithChildren
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/runs': typeof RunsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/help/chat': typeof HelpChatRoute
  '/help/contact': typeof HelpContactRoute
  '/help/faq': typeof HelpFaqRoute
  '/help/tutorial': typeof HelpTutorialRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/projects': typeof PortalProjectsRoute
  '/portal/testbeds': typeof PortalTestbedsRoute
  '/portal/tools': typeof PortalToolsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tools/orca': typeof ToolsOrcaRouteWithChildren
  '/tools/performance': typeof ToolsPerformanceRouteWithChildren
  '/tools/qa-genius': typeof ToolsQaGeniusRouteWithChildren
  '/tools/qe': typeof ToolsQeRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tools/orca/agents': typeof ToolsOrcaAgentsRoute
  '/tools/orca/logs': typeof ToolsOrcaLogsRoute
  '/tools/orca/swarms': typeof ToolsOrcaSwarmsRoute
  '/tools/performance/reports': typeof ToolsPerformanceReportsRoute
  '/tools/performance/scenarios': typeof ToolsPerformanceScenariosRoute
  '/tools/qa-genius/history': typeof ToolsQaGeniusHistoryRoute
  '/tools/qa-genius/library': typeof ToolsQaGeniusLibraryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/register'
    | '/runs'
    | '/schedule'
    | '/settings'
    | '/help/chat'
    | '/help/contact'
    | '/help/faq'
    | '/help/tutorial'
    | '/portal/admin'
    | '/portal/projects'
    | '/portal/testbeds'
    | '/portal/tools'
    | '/projects/$projectId'
    | '/tools/orca'
    | '/tools/performance'
    | '/tools/qa-genius'
    | '/tools/qe'
    | '/projects/'
    | '/tools/orca/agents'
    | '/tools/orca/logs'
    | '/tools/orca/swarms'
    | '/tools/performance/reports'
    | '/tools/performance/scenarios'
    | '/tools/qa-genius/history'
    | '/tools/qa-genius/library'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/runs'
    | '/schedule'
    | '/settings'
    | '/help/chat'
    | '/help/contact'
    | '/help/faq'
    | '/help/tutorial'
    | '/portal/admin'
    | '/portal/projects'
    | '/portal/testbeds'
    | '/portal/tools'
    | '/projects/$projectId'
    | '/tools/orca'
    | '/tools/performance'
    | '/tools/qa-genius'
    | '/tools/qe'
    | '/projects'
    | '/tools/orca/agents'
    | '/tools/orca/logs'
    | '/tools/orca/swarms'
    | '/tools/performance/reports'
    | '/tools/performance/scenarios'
    | '/tools/qa-genius/history'
    | '/tools/qa-genius/library'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/projects'
    | '/register'
    | '/runs'
    | '/schedule'
    | '/settings'
    | '/help/chat'
    | '/help/contact'
    | '/help/faq'
    | '/help/tutorial'
    | '/portal/admin'
    | '/portal/projects'
    | '/portal/testbeds'
    | '/portal/tools'
    | '/projects/$projectId'
    | '/tools/orca'
    | '/tools/performance'
    | '/tools/qa-genius'
    | '/tools/qe'
    | '/projects/'
    | '/tools/orca/agents'
    | '/tools/orca/logs'
    | '/tools/orca/swarms'
    | '/tools/performance/reports'
    | '/tools/performance/scenarios'
    | '/tools/qa-genius/history'
    | '/tools/qa-genius/library'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  RunsRoute: typeof RunsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  PortalAdminRoute: typeof PortalAdminRoute
  PortalProjectsRoute: typeof PortalProjectsRoute
  PortalTestbedsRoute: typeof PortalTestbedsRoute
  PortalToolsRoute: typeof PortalToolsRoute
  ToolsOrcaRoute: typeof ToolsOrcaRouteWithChildren
  ToolsPerformanceRoute: typeof ToolsPerformanceRouteWithChildren
  ToolsQaGeniusRoute: typeof ToolsQaGeniusRouteWithChildren
  ToolsQeRoute: typeof ToolsQeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/tools/qe': {
      id: '/tools/qe'
      path: '/tools/qe'
      fullPath: '/tools/qe'
      preLoaderRoute: typeof ToolsQeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/qa-genius': {
      id: '/tools/qa-genius'
      path: '/tools/qa-genius'
      fullPath: '/tools/qa-genius'
      preLoaderRoute: typeof ToolsQaGeniusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/performance': {
      id: '/tools/performance'
      path: '/tools/performance'
      fullPath: '/tools/performance'
      preLoaderRoute: typeof ToolsPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/orca': {
      id: '/tools/orca'
      path: '/tools/orca'
      fullPath: '/tools/orca'
      preLoaderRoute: typeof ToolsOrcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/portal/tools': {
      id: '/portal/tools'
      path: '/portal/tools'
      fullPath: '/portal/tools'
      preLoaderRoute: typeof PortalToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/testbeds': {
      id: '/portal/testbeds'
      path: '/portal/testbeds'
      fullPath: '/portal/testbeds'
      preLoaderRoute: typeof PortalTestbedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/projects': {
      id: '/portal/projects'
      path: '/portal/projects'
      fullPath: '/portal/projects'
      preLoaderRoute: typeof PortalProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/tutorial': {
      id: '/help/tutorial'
      path: '/tutorial'
      fullPath: '/help/tutorial'
      preLoaderRoute: typeof HelpTutorialRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/faq': {
      id: '/help/faq'
      path: '/faq'
      fullPath: '/help/faq'
      preLoaderRoute: typeof HelpFaqRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/contact': {
      id: '/help/contact'
      path: '/contact'
      fullPath: '/help/contact'
      preLoaderRoute: typeof HelpContactRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/chat': {
      id: '/help/chat'
      path: '/chat'
      fullPath: '/help/chat'
      preLoaderRoute: typeof HelpChatRouteImport
      parentRoute: typeof HelpRoute
    }
    '/tools/qa-genius/library': {
      id: '/tools/qa-genius/library'
      path: '/library'
      fullPath: '/tools/qa-genius/library'
      preLoaderRoute: typeof ToolsQaGeniusLibraryRouteImport
      parentRoute: typeof ToolsQaGeniusRoute
    }
    '/tools/qa-genius/history': {
      id: '/tools/qa-genius/history'
      path: '/history'
      fullPath: '/tools/qa-genius/history'
      preLoaderRoute: typeof ToolsQaGeniusHistoryRouteImport
      parentRoute: typeof ToolsQaGeniusRoute
    }
    '/tools/performance/scenarios': {
      id: '/tools/performance/scenarios'
      path: '/scenarios'
      fullPath: '/tools/performance/scenarios'
      preLoaderRoute: typeof ToolsPerformanceScenariosRouteImport
      parentRoute: typeof ToolsPerformanceRoute
    }
    '/tools/performance/reports': {
      id: '/tools/performance/reports'
      path: '/reports'
      fullPath: '/tools/performance/reports'
      preLoaderRoute: typeof ToolsPerformanceReportsRouteImport
      parentRoute: typeof ToolsPerformanceRoute
    }
    '/tools/orca/swarms': {
      id: '/tools/orca/swarms'
      path: '/swarms'
      fullPath: '/tools/orca/swarms'
      preLoaderRoute: typeof ToolsOrcaSwarmsRouteImport
      parentRoute: typeof ToolsOrcaRoute
    }
    '/tools/orca/logs': {
      id: '/tools/orca/logs'
      path: '/logs'
      fullPath: '/tools/orca/logs'
      preLoaderRoute: typeof ToolsOrcaLogsRouteImport
      parentRoute: typeof ToolsOrcaRoute
    }
    '/tools/orca/agents': {
      id: '/tools/orca/agents'
      path: '/agents'
      fullPath: '/tools/orca/agents'
      preLoaderRoute: typeof ToolsOrcaAgentsRouteImport
      parentRoute: typeof ToolsOrcaRoute
    }
  }
}

interface HelpRouteChildren {
  HelpChatRoute: typeof HelpChatRoute
  HelpContactRoute: typeof HelpContactRoute
  HelpFaqRoute: typeof HelpFaqRoute
  HelpTutorialRoute: typeof HelpTutorialRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpChatRoute: HelpChatRoute,
  HelpContactRoute: HelpContactRoute,
  HelpFaqRoute: HelpFaqRoute,
  HelpTutorialRoute: HelpTutorialRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ToolsOrcaRouteChildren {
  ToolsOrcaAgentsRoute: typeof ToolsOrcaAgentsRoute
  ToolsOrcaLogsRoute: typeof ToolsOrcaLogsRoute
  ToolsOrcaSwarmsRoute: typeof ToolsOrcaSwarmsRoute
}

const ToolsOrcaRouteChildren: ToolsOrcaRouteChildren = {
  ToolsOrcaAgentsRoute: ToolsOrcaAgentsRoute,
  ToolsOrcaLogsRoute: ToolsOrcaLogsRoute,
  ToolsOrcaSwarmsRoute: ToolsOrcaSwarmsRoute,
}

const ToolsOrcaRouteWithChildren = ToolsOrcaRoute._addFileChildren(
  ToolsOrcaRouteChildren,
)

interface ToolsPerformanceRouteChildren {
  ToolsPerformanceReportsRoute: typeof ToolsPerformanceReportsRoute
  ToolsPerformanceScenariosRoute: typeof ToolsPerformanceScenariosRoute
}

const ToolsPerformanceRouteChildren: ToolsPerformanceRouteChildren = {
  ToolsPerformanceReportsRoute: ToolsPerformanceReportsRoute,
  ToolsPerformanceScenariosRoute: ToolsPerformanceScenariosRoute,
}

const ToolsPerformanceRouteWithChildren =
  ToolsPerformanceRoute._addFileChildren(ToolsPerformanceRouteChildren)

interface ToolsQaGeniusRouteChildren {
  ToolsQaGeniusHistoryRoute: typeof ToolsQaGeniusHistoryRoute
  ToolsQaGeniusLibraryRoute: typeof ToolsQaGeniusLibraryRoute
}

const ToolsQaGeniusRouteChildren: ToolsQaGeniusRouteChildren = {
  ToolsQaGeniusHistoryRoute: ToolsQaGeniusHistoryRoute,
  ToolsQaGeniusLibraryRoute: ToolsQaGeniusLibraryRoute,
}

const ToolsQaGeniusRouteWithChildren = ToolsQaGeniusRoute._addFileChildren(
  ToolsQaGeniusRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRouteWithChildren,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  RunsRoute: RunsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  PortalAdminRoute: PortalAdminRoute,
  PortalProjectsRoute: PortalProjectsRoute,
  PortalTestbedsRoute: PortalTestbedsRoute,
  PortalToolsRoute: PortalToolsRoute,
  ToolsOrcaRoute: ToolsOrcaRouteWithChildren,
  ToolsPerformanceRoute: ToolsPerformanceRouteWithChildren,
  ToolsQaGeniusRoute: ToolsQaGeniusRouteWithChildren,
  ToolsQeRoute: ToolsQeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
